### TensorFlow Basic Syntax



In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.3


In [3]:
hello = tf.constant('Hello')

In [4]:
world = tf.constant('World')

In [6]:
type(hello) # Tensor object

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [12]:
result

b'HelloWorld'

In [13]:
a = tf.constant(10)
b = tf.constant(59)

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

69

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4), 10) #creates a 1D array

In [19]:
myzeros = tf.zeros((4,4))
myone = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [23]:
my_ops = [const,fill_mat,myzeros,myone,myrandn,myrandu]

In [24]:
sess = tf.InteractiveSession()

In [26]:
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.13951853  0.36348054 -0.14906807  0.5961779 ]
 [ 1.0082103   0.50487316 -1.270035    0.1626958 ]
 [ 0.19472098 -0.4446622  -0.47560945 -1.4950929 ]
 [ 1.7666804   0.60944474  0.35727268  0.4345443 ]]
[[0.69752204 0.2830516  0.3418405  0.85784733]
 [0.7870823  0.75387204 0.89911115 0.37024844]
 [0.36459386 0.89228237 0.7433932  0.89691544]
 [0.74790704 0.13284695 0.01993489 0.996959  ]]


In [27]:
a = tf.constant([[1,2],[3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10],[100]])

In [30]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [31]:
result = tf.matmul(a,b)

In [32]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [33]:
result.eval()

array([[210],
       [430]], dtype=int32)